<a href="https://colab.research.google.com/github/Cristinamulas/Tensorflow-2.0-Notes/blob/master/TensorFlow2_0_book1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
import tensorflow as tf
import numpy as np

In [5]:
tf.__version__

'2.3.0'

## Defining a constant

In [7]:
tensor_20 = tf.constant([[23,4],[34,44]])

In [8]:
tensor_20.shape

TensorShape([2, 2])

## Getting the values of a constant

In [9]:
numpy_tensor = np.array([[23,5],[88,6]])

In [10]:
tensor_from_numpy = tf.constant(numpy_tensor)

In [12]:
tensor_20.numpy()

array([[23,  4],
       [34, 44]], dtype=int32)

## Defining a variable

In [14]:
tf2_variable = tf.Variable([[1,2],[4,5]])

In [15]:
tf2_variable

<tf.Variable 'Variable:0' shape=(2, 2) dtype=int32, numpy=
array([[1, 2],
       [4, 5]], dtype=int32)>

In [18]:
tf2_variable[0,1].assign(100)

<tf.Variable 'UnreadVariable' shape=(2, 2) dtype=int32, numpy=
array([[  1, 100],
       [  4,   5]], dtype=int32)>

## Operation with tensors

In [19]:
tensor = tf.constant([[1,2],[3,4]])

In [20]:
tensor + 2

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[3, 4],
       [5, 6]], dtype=int32)>

In [21]:
tensor * 5

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 5, 10],
       [15, 20]], dtype=int32)>

## Using Numpy functions on TensorFlow tensors

In [22]:
np.square(tensor)

array([[ 1,  4],
       [ 9, 16]], dtype=int32)

In [23]:
np.sqrt(tensor)

array([[1.        , 1.41421356],
       [1.73205081, 2.        ]])

In [24]:
# dot product
np.dot(tensor, tensor_20)

array([[ 91,  92],
       [205, 188]], dtype=int32)

## Strings

In [26]:
tf_string = tf.constant("hello")

In [27]:
tf_string 

<tf.Tensor: shape=(), dtype=string, numpy=b'hello'>

In [31]:
tf.strings.length(tf_string)

<tf.Tensor: shape=(), dtype=int32, numpy=5>

In [32]:
tf.strings.unicode_decode(tf_string, "UTF8")

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([104, 101, 108, 108, 111], dtype=int32)>

In [33]:
tf_sting_array = tf.constant(["hello",'word','now'])

In [34]:
for i in tf_sting_array:
  print(i)

tf.Tensor(b'hello', shape=(), dtype=string)
tf.Tensor(b'word', shape=(), dtype=string)
tf.Tensor(b'now', shape=(), dtype=string)
